version: '3'

include:
  - docker/docker-compose.base.yml

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: api
    ports:
      - '8000:8000'
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - db
