version: '3'

include:
  - docker/docker-compose.base.yml

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - '8000:8000'
    env_file:
      - .env.prod
    depends_on:
      - db
