swagger: "2.0"
info:
  title: TubeCafe's API
  version: 1.0.0
  description: The backend app for TubeCafe, a video sharing platform.
  contact:
    name: Mcvean Soans (McTechie)
    url: https://github.com/McTechie
basePath: /api/v1
paths:
  /admin/action-logs:
    get:
      tags:
        - Admin
  /auth/register:
    post:
      tags:
        - Auth
  /auth/login:
    post:
      tags:
        - Auth
  /auth/logout:
    post:
      tags:
        - Auth
  /auth/refresh-token:
    post:
      tags:
        - Auth
  /auth/change-password:
    post:
      tags:
        - Auth
  /auth/me:
    get:
      tags:
        - Auth
  /c/:username:
    get:
      tags:
        - Channel
  /c/:username/videos:
    get:
      tags:
        - Channel
  /u/:
    get:
      tags:
        - User
  /u/update-avatar:
    put:
      tags:
        - User
  /u/update-cover-image:
    put:
      tags:
        - User
  /u/:id:
    get:
      tags:
        - User
    put:
      tags:
        - User
    delete:
      tags:
        - User
  /u/:id/watch-history:
    get:
      tags:
        - User
  /v/:
    get:
      tags:
        - Video
  /v/upload:
    post:
      tags:
        - Video
  /v/toggle-publish/:id:
    put:
      tags:
        - Video
  /v/:id:
    get:
      tags:
        - Video
